### PR TITLE
Change API loglevel to INFO.

### PR DESCRIPTION
**Pull request by cmfcruz**
Change-type: patch
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

### CODE REVIEW

**Comment by cmfcruz** [comment]
@balena-ci I self-certify!

**Comment by joshbwlng** [comment]
@balena-ci retest

**Comment by cmfcruz** [comment]
@balena-ci retest

**Comment by cmfcruz** [comment]
Closing this PR in favor of just setting the lov level using environment variables.

**Pull request closed without merging**
