### PR TITLE
UI: Improve image rendering

### PR DESCRIPTION
**Pull request by LucianBuzzo**
This change keeps the generated blob source data in cache in the
browser, reducing server load and visually disruptive re-renders.
This cache is ephemeeral and flushed on a browser navigation.
The ideal solution is to use cookies to authenticate files instead of
fetching blob data and assembling it in the browser.

Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

***

Caches images posted in messages, instead of reloading them from the API every time. This fixes distracting resize events in timelines and interleaved lenses.

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Comment by joshbwlng** [comment]
Uploaded images are currently not being resized

**Comment by joshbwlng** [comment]
Things look to be working as expected, but need to double-check code changes one more time just in case

**Comment by joshbwlng** [comment]
@balena-ci rebase

**Review by joshbwlng — APPROVED** [review]

**Pull request merged**
