### PR TITLE
[UI]: add localTime on username tooltips

### PR DESCRIPTION
**Pull request by aethernet**
[UI]: add localTime and City on username tooltips

change-type: patch

### CODE REVIEW

**Comment by aethernet** [comment]
Same PR as https://github.com/product-os/jellyfish/pull/9130 but with a cleaner git history.
Cursor_and__2__improvement-preloading-imag______Jellyfish

**Comment by aethernet** [comment]
now versionist is happy but deployment fails and i have no clue why. Doesn't looks like an issue with the code but with the CI system itself.

**Comment by joshbwlng** [comment]
@aethernet Yep, this is probably just an issue with CI itself. Jellyfish has a complex CI that depends on balena builders, downloading images, etc so its not uncommon for CI to fail for reasons unrelated to code changes. :tired_face: In those cases, you can retry the workflow.

**Comment by aethernet** [comment]
actually totally my fault, i forgot to update the tests for those components

**Comment by joshbwlng** [comment]
@aethernet You can run tests locally with `cd apps/ui && npm run test` to find these quick and not have to wait on our (slow) CI.

**Comment by aethernet** [comment]
i fixed those before the weekend, but forgot to push ^^

**Comment by aethernet** [comment]
it's ready to go

**Review by joshbwlng — APPROVED** [review]

**Comment by joshbwlng** [comment]
@balena-ci rebase

**Pull request merged**
