### PR TITLE
add types to check-run lense

### PR DESCRIPTION
**Pull request by Hades32**
~~also traverse deeper than just 3 levels~~

### CODE REVIEW

**Comment by Hades32** [comment]
actually I started this PR to get history navigation for the graph, but seems it's a bit tricky. I added `javascript:window.history.pushState(...)` as the href, but that didn't lead to react's router to actually do something, so it seems we need to hook into the react context from the Mermaid click handler...

**Comment by Hades32** [comment]
@balena-ci retest

**Comment by Hades32** [comment]
@balena-ci retest

**Review by LucianBuzzo — APPROVED** [review]

**Comment by Hades32** [comment]
@balena-ci retest

**Comment by Hades32** [comment]
Damn...
image
But code looks ok:
```
graph TD
8381095a-a103-4e23-84c7-0e0a1f718dd0(<i>commit@1.0.0</i><br/>Commit ce185c9b for PR patch: Update external-major (major)<br/>v1.0.0) -->|was built into| 59298e3e-dc8c-4a46-8f66-d7467be7b088(<i>type-balena-io-t-balena-app-source@1.0.4</i><br/>Transformer worker<br/>v0.19.20-pr-ce185c9b48941011c8216475f022402f9d3ce6c8)
59298e3e-dc8c-4a46-8f66-d7467be7b088(<i>type-balena-io-t-balena-app-source@1.0.4</i><br/>Transformer worker<br/>v0.19.20-pr-ce185c9b48941011c8216475f022402f9d3ce6c8) -->|was built into| 54e20516-8c14-4871-bf6e-78da70b9b086(<i>type-balena-io-t-balena-app-release@1.0.0</i><br/>type-balena-io-t-balena-app-release-product-os-transformer-worker<br/>v0.19.20-pr-ce185c9b48941011c8216475f022402f9d3ce6c8)
click 54e20516-8c14-4871-bf6e-78da70b9b086 "/type-balena-io-t-balena-app-release-product-os-transformer-worker@0.19.20-pr-ce185c9b48941011c8216475f022402f9d3ce6c8"
click 59298e3e-dc8c-4a46-8f66-d7467be7b088 "/type-balena-io-t-balena-app-source-product-os-transformer-worker@0.19.20-pr-ce185c9b48941011c8216475f022402f9d3ce6c8"
click 8381095a-a103-4e23-84c7-0e0a1f718dd0 "/commit-ce185c9b48941011c8216475f022402f9d3ce6c8-pull-request-pr-kwdoe6rjsm4vfdut@1.0.0"
```

**Pull request merged**
