### PR TITLE
Create a generic chart lens and use it for pull requests

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

Adds customizable charting, provided by https://github.com/plotly/react-chart-editor

charts

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

### CODE REVIEW

**Review by StefKors — DISMISSED** [review]
LGTM

**Review by mbalamat — COMMENTED** [review]
@grahammcculloch @LucianBuzzo @ljewalsh can we somehow test this differently (eg e2e) because plotly fails even if I try to provide the window property that it needs, in general if it's running outside of a browser context it fails.

**Review by grahammcculloch — COMMENTED** [review]
Code looks good to me - thanks for adding an e2e test! Can you do one additional thing and then I'll approve this PR? Can you install [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) as a dev dependency and use it to create a diagram of the new jellyfish main bundle (the bundle created using `make build-ui`) and post a screenshot of that in this PR together with the equivalent screenshot of the bundle map generated from master. And then include in the comment the total bundled size on master and on this branch. I'm interested in what effect this branch has on the bundle size!

**Review by grahammcculloch — DISMISSED** [review]
Ship it!

**Review by grahammcculloch — APPROVED** [review]

**Pull request merged**
