### PR TITLE
UI cleanup

### PR DESCRIPTION
**Pull request by karaxuna**
- Move selectors to separate file;
- Remove core folder, extract store from it;
- Create sdk, errorReporter and analytics in main App component instead of creating inside a file and use them via `useSetup` or `withSetup`;
- Remove unused node modules;

*Note:* Diff is due to module removal that caused deletion of many lines in `package-lock.json`.

Change-type: patch

### CODE REVIEW

**Comment by karaxuna** [comment]
@balena-ci rebase

**Comment by karaxuna** [comment]
@balena-ci rebase

**Comment by joshbwlng** [comment]
@balena-ci rebase

**Comment by karaxuna** [comment]
@balena-ci I self certify!

**Pull request merged**
