### PR TITLE
Update to latest worker v33

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
Currently failing due to a buggy `thread` schema, which is being fixed in this PR https://github.com/product-os/jellyfish-worker/pull/1723

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Comment by joshbwlng** [comment]
@balena-ci rebase

**Comment by joshbwlng** [comment]
Already bumped to v33 in separate PR

**Pull request closed without merging**
