### PR TITLE
Add another row of emojis

### PR DESCRIPTION
**Pull request by inwenc**
Change-type: minor

image

***
**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

### CODE REVIEW

**Comment by joshbwlng** [comment]
@inwenc UI container build is failing with:
```
[ui]               lib/components/Event/Message/Reactions.tsx(4,18): error TS6133: 'Flex' is declared but its value is never read.
```

**Comment by ramirogm** [comment]
@inwenc I made some fixes to the build process that I think could have made the build above to fail; I suggest to rebase and see if that fixes the tests.

**Comment by inwenc** [comment]
it worked. thanks @ramirogm

**Review by ramirogm — APPROVED** [review]
👍🏻

**Pull request merged**
