### PR TITLE
Allow env to be undefined

### PR DESCRIPTION
**Pull request by StefKors**
Because react isn't compiled by Webpack, env vars aren't included during unit tests. This PR allows these to be undefined if "env" doesn't exist.

This error showed up after updating AVA and Sinon in PR #3160

Change-type: patch
Signed-off-by: Stef Kors <stef@balena.io>

### CODE REVIEW

**Review by grahammcculloch — COMMENTED** [review]
Whilst this approach may prevent unit tests from falling over, there are various ways to allow tests to make use of environment variables. See [this thread](https://github.com/vuejs/vue-test-utils/issues/193) for some examples.

I think in the long run we'll be better off if we _can_ support environment variables in UI unit tests.

**Review by ffissore — APPROVED** [review]
Yeah, double checked even using `_.get` and `pirates` keeps complaining. What is pirates?
I'm good to have this code merged

**Review by grahammcculloch — CHANGES_REQUESTED** [review]
Just needs a small logic tweak to be fully equivalent to the previous logic.

**Review by grahammcculloch — COMMENTED** [review]
Just spotted one issue that might have slipped through the refactor (see inline comment)

**Review by grahammcculloch — CHANGES_REQUESTED** [review]
Er... still not quite right! (Again, see inline comment)

**Review by grahammcculloch — APPROVED** [review]

**Pull request merged**
