### PR TITLE
Upgrade to webpack 5

### PR DESCRIPTION
**Pull request by karaxuna**
Change-type: minor

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

### CODE REVIEW

**Comment by karaxuna** [comment]
@balena-ci rebase

**Comment by karaxuna** [comment]
@balena-ci retest

**Comment by karaxuna** [comment]
@balena-ci rebase

**Comment by LucianBuzzo** [comment]
LGTM just need to get these tests passing

**Comment by karaxuna** [comment]
@balena-ci rebase

**Comment by karaxuna** [comment]
@balena-ci rebase

**Comment by karaxuna** [comment]
@balena-ci rebase

**Comment by karaxuna** [comment]
@balena-ci I self certify!

**Comment by karaxuna** [comment]
@balena-ci rebase

**Pull request merged**
