### PR TITLE
Activate ui tests

### PR DESCRIPTION
**Pull request by karaxuna**
Change-type: major

---

Denoting this as a major change as the return data from `/api/v2/oauth/` is being slightly changed to match the structure returned from other endpoints.

### CODE REVIEW

**Comment by karaxuna** [comment]
@balena-ci rebase

**Comment by joshbwlng** [comment]
@balena-ci rebase

**Comment by karaxuna** [comment]
@balena-ci retest

**Comment by karaxuna** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
Everything is passing when tested in local compose, maybe balenaCI is having a bad day.

**Review by joshbwlng — APPROVED** [review]

**Pull request merged**
