### PR TITLE
Replace react-virtualized with react-virtuoso in the list lens

### PR DESCRIPTION
**Pull request by edufschmidt**
This PR replaces the `react-virtualized` module with `react-virtuoso` for list virtualization, completely dropping the former. Virtuoso has some advantages over other virtualization modules, namely it can automatically deal with non-fixed row heights, as well as dynamically-sized items. Moreover, it provides out-of-the-box support for infinite loading, which is quite convenient, allowing us to remove a bunch of code.

Change-type: minor

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

### CODE REVIEW

**Comment by edufschmidt** [comment]
@balena-ci retest

**Comment by edufschmidt** [comment]
@balena-ci retest

**Comment by edufschmidt** [comment]
@balena-ci retest

**Comment by edufschmidt** [comment]
@balena-ci retest

**Comment by edufschmidt** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
I'll rebase this on top of current master, as there are a few changes to pagination we need to include

**Comment by LucianBuzzo** [comment]
@balena-ci I self-certify!

**Review by LucianBuzzo — APPROVED** [review]

**Pull request merged**
