### PR TITLE
Update to rendition v25.x

### PR DESCRIPTION
**Pull request by LucianBuzzo**
This update also means we need to update the chat widget and ui
components libraries, as they have a peer dependency on rendition.

Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

### CODE REVIEW

**Comment by karaxuna** [comment]
@balena-ci retest

**Comment by karaxuna** [comment]
Looks like react is duplicated by grommet.

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci I self-certify!

**Pull request merged**
