### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Ereski**
Change-type: major
Signed-off-by: Carol Schulze <carol@balena.io>

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

### CODE REVIEW

**Comment by Ereski** [comment]
Only one type error:

```
lib/bootstrap.ts:156:31 - error TS2345: Argument of type 'Redis' is not assignable to parameter of type 'CacheOptions'.
  Types of property 'socket' are incompatible.
    Type '{ host: string; port: string; }' is not assignable to type 'RedisSocketOptions | undefined'.
      Type '{ host: string; port: string; }' is not assignable to type 'RedisSocketCommonOptions & RedisTlsSocketOptions'.
        Property 'tls' is missing in type '{ host: string; port: string; }' but required in type 'RedisTlsSocketOptions'.
```

Weird, none of the other packages had issues

**Comment by Ereski** [comment]
Not setting `tls` should be valid:

```ts
declare type RedisNetSocketOptions = Partial<net.SocketConnectOpts> & {
    tls?: false;
};
export interface RedisTlsSocketOptions extends tls.ConnectionOptions {
    tls: true;
}
export declare type RedisSocketOptions = RedisSocketCommonOptions & (RedisNetSocketOptions | RedisTlsSocketOptions);
```

**Comment by Ereski** [comment]
Why is TS saying:

```
RedisSocketCommonOptions & RedisTlsSocketOptions
```

Instead of

```
RedisSocketCommonOptions & (RedisNetSocketOptions | RedisTlsSocketOptions)
```

Like in the declaration file?

**Comment by Ereski** [comment]
So, the code as it is **should** work but TS is complaining because somehow it has the wrong definition for `RedisSocketOptions`.

**Comment by Ereski** [comment]
Hmm, so manually setting tls to neither true nor false, nor forcing the call to accept the options as is makes it actually work. It fails to connect to redis

**Comment by karaxuna** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
@balena-ci retest

**Review by LucianBuzzo — APPROVED** [review]

**Pull request merged**
