### PR TITLE
Merge action-server and server services into a single instance

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Since both services have the same dependencies, running the core, worker
and queue modules as well as loading plugins, the only realy difference
is that the server can receive external http traffic. Unifying the two
services is a no-brainer and brings us closer to being able to create
a unified jellyfish system, with less indirection and more simplicity.

Change-type: major
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

***

## Tests
- Passed (2021-11-05): https://ci.product-os.io/builds/5085

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
I think bulldozer closed this by mistake

**Comment by Hades32** [comment]
oh, that's weird...

**Comment by Hades32** [comment]
rebased to get newest worker with fixes.
note to self: hope I resolved the merge conflicts semantically correct. If not, this was the commit before: https://github.com/product-os/jellyfish/commit/a22a311a03be0d3c67270f7729c34a6b875bf2d5

**Comment by joshbwlng** [comment]
@balena-ci retest

**Review by joshbwlng — APPROVED** [review]

**Comment by joshbwlng** [comment]
@balena-ci republish

**Comment by joshbwlng** [comment]
@balena-ci republish

**Comment by joshbwlng** [comment]
@balena-ci republish

**Comment by joshbwlng** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by stathismor** [comment]
@balena-ci republish

**Pull request merged**
