### PR TITLE
Add livechat as a page to JF

### PR DESCRIPTION
**Pull request by karaxuna**
Change-type: minor

***

Add `/livechat` route. This is part of [ui and livechat merge](https://jel.ly.fish/improvement-merge-ui-livechat-services-3e61550).

tmp

### CODE REVIEW

**Comment by karaxuna** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@karaxuna Nice, any thoughts on how to stop the sidebar from showing?

**Comment by karaxuna** [comment]
> @karaxuna Nice, any thoughts on how to stop the sidebar from showing?

@LucianBuzzo I'll move livechat component out from the layout.

**Comment by karaxuna** [comment]
@LucianBuzzo done, removed sidebar.

**Review by LucianBuzzo — APPROVED** [review]

**Pull request merged**
