### PR TITLE
Allow account contracts to have a null name field

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

### CODE REVIEW

**Review by joshbwlng — APPROVED** [review]

**Comment by joshbwlng** [comment]
@LucianBuzzo TypeScript build failing with:
```
#19 8.505 lib/bootstrap.ts(179,32): error TS2345: Argument of type 'import("/usr/src/jellyfish/apps/server/node_modules/@balena/jellyfish-core/build/kernel").Kernel' is not assignable to parameter of type 'import("/usr/src/jellyfish/apps/server/node_modules/@balena/jellyfish-queue/node_modules/@balena/jellyfish-core/build/kernel").Kernel'.
#19 8.506 lib/bootstrap.ts(180,32): error TS2345: Argument of type 'import("/usr/src/jellyfish/apps/server/node_modules/@balena/jellyfish-core/build/kernel").Kernel' is not assignable to parameter of type 'import("/usr/src/jellyfish/apps/server/node_modules/@balena/jellyfish-queue/node_modules/@balena/jellyfish-core/build/kernel").Kernel'.
#19 8.506   Types have separate declarations of a private property 'backend'.
```

Saw this earlier today in https://github.com/product-os/jellyfish/pull/8049 and have since opened https://github.com/product-os/jellyfish/pull/8052 to try and get everything in line. That PR is failing with an error about Redis env vars which I know @Ereski changed recently so maybe she can help get this sorted.

**Comment by Ereski** [comment]
Poorly timed upgrade :/

The change is just to put `host` and `port` inside a `socket` object:

```js
{
  password: ...,
  socket: {
    host: ...,
    port: ....,
  }
}
```

I'll propagate the update :+1:

**Comment by Ereski** [comment]
Ah looks like everything else is updated already. Nice

**Comment by Ereski** [comment]
actually ui-components has some quite outdated deps

**Comment by joshbwlng** [comment]
Moved to https://github.com/product-os/jellyfish/pull/8058

**Pull request closed without merging**
