### PR TITLE
Bump internal packages

### PR DESCRIPTION
**Pull request by joshbwlng**
Change-type: patch
Signed-off-by: Josh Bowling <josh@balena.io>

***

Bump a few internal packages, mainly to ensure that we only have one copy of the `Kernel` type definition and that it is the latest. Otherwise, we end up with build errors when attempting to build `apps/server`.

### CODE REVIEW

**Comment by joshbwlng** [comment]
@balena-ci I self certify!

**Comment by joshbwlng** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
@Ereski Getting this type error when setting up cache:
```
#19 12.88 lib/bootstrap.ts(156,31): error TS2345: Argument of type 'Redis' is not assignable to parameter of type 'CacheOptions'.
#19 12.88   Types of property 'socket' are incompatible.
#19 12.88     Type '{ host: string; port: string; }' is not assignable to type 'RedisSocketOptions | undefined'.
#19 12.88       Type '{ host: string; port: string; }' is not assignable to type 'RedisSocketCommonOptions & RedisTlsSocketOptions'.
#19 12.88         Property 'tls' is missing in type '{ host: string; port: string; }' but required in type 'RedisTlsSocketOptions'.
```

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Comment by joshbwlng** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
Moved to https://github.com/product-os/jellyfish/pull/8058

**Pull request closed without merging**
